apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: mern
spec:
  volumeName: host-pv
  storageClassName: standered
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
          