apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standered
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/
    type: DirectoryOrCreate
